import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AddToCart from "./components/ThemeToggle";
import Link from "next/link";
import Navbar from "./Navbar";
import ThemeToggle from "./components/ThemeToggle";
import AuthProvider from "./auth/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <AuthProvider>
          <div className=" flex justify-between mb-10">
            <Navbar />
            <ThemeToggle />
          </div>
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
